### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by yo-aiv1** [DeLuks2006/PasswdMan#1]
Are you open to contributions, or would you prefer to work on and maintain it by yourself?
i'll just wanna work on some of your TODOs

**Comment by DeLuks2006** [comment]
Hey, really happy that you're interested in the project, however I originally wanted it to be a solo project because I'm still bad at C but if you want, you can of course contribute to it by correcting my existing code and/or creating issues. 

_Or you could help me out by creating a cmake file._ (that would be awesome)

**Comment by yo-aiv1** [comment]
hii, regarding 'correcting my existing', did you mean forking the repo and making changes, or simply pointing out the issues or improvement to you? The same question applies to the CMake file, although it's easy

**Comment by DeLuks2006** [comment]
both, both is good. 😂

**Comment by DeLuks2006** [comment]
I'll do some changes later today so I'd reccommend you do the cmake file later when I'm done with the changes.

Also if you want we can discuss this further on discord. :)
